version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: spareparts_user
      POSTGRES_PASSWORD: spareparts_password
      POSTGRES_DB: spareparts_db
      
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
      DATABASE_URL: postgres://spareparts_user:spareparts_password@db:5432/spareparts_db
    depends_on:
      - db
      
  frontend:
    build: ./Frontend/react-app
    command: npm run dev -- --host 0.0.0.0 --port 3000
    volumes:
      - ./Frontend/react-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  postgres_data_dev: